var am = ['bounceInLeft',
    'bounceInRight', 'bounceInDown', 'bounceInUp', 'fadeIn',
    'fadeInDown',
    'fadeInDownBig',
    'fadeInLeft',
    'fadeInLeftBig',
    'fadeInRight',
    'fadeInRightBig',
    'fadeInUp',
    'fadeInUpBig', 'flipInX',
    'flipInY', 'lightSpeedIn', 'rotateIn', 'rotateInDownLeft', 'rotateInDownRight',
    'rotateInUpLeft',
    'rotateInUpRight', 'zoomIn',
    'zoomInDown',
    'zoomInLeft',
    'zoomInRight',
    'zoomInUp', 'slideInDown',
    'slideInLeft',
    'slideInRight',
    'slideInUp',
    'bounce',
    'flash',
    'pulse',
    'rubberBand',
    'shake',
    'headShake',
    'swing',
    'tada',
    'wobble'
];